# This is the name of the file
name: Ci/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where workflow runs
        default: "dev"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "build the code from docker"
    
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "testing the container"
    
  deploy:
    if: inputs.environment == 'dev'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the container
        run: echo "docker container deploying the app"
