name: DevSecOps End to end pipeline

on:
    push:
        branches: [main]

jobs:
    # CI (Continuous integration with Securith Scanning)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:    
        uses: ./.github/workflows/secrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml
    
    # Build Once when Security Scans are complete
    build:
        needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

