# This is workflow name
name: Hello

# runs on a trigger
on:
  push:
    branches: [main]

# This are the jobs inside the workflow
jobs:
# This is the name of the jobs
  greet:
# This is github runner (each 
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show the details of docker and python version
        run: docker --version && python --version
